# Generated by Django 4.2.5 on 2023-11-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tributario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='jefeVentas.documentotributario')),
            ],
        ),
    ]
