# Generated by Django 4.2.7 on 2023-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jefeVentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, default='default_imagen.png', null=True, upload_to='product_img'),
        ),
    ]
