# Generated by Django 4.2.7 on 2023-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
