# Generated by Django 4.2.7 on 2023-11-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vendedor.caja'),
        ),
    ]
