# Generated by Django 4.2.7 on 2023-12-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0002_caja_monto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='monto',
            new_name='monto_inicial',
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
