# Generated by Django 4.2.7 on 2023-11-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0003_producto_sku_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
