# Generated by Django 4.2.7 on 2023-12-22 05:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0004_alter_venta_iva_alter_venta_precio_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.IntegerField()),
                ('iva', models.FloatField()),
                ('precio_total', models.IntegerField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.tipodocumentotributario')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.vendedor')),
            ],
        ),
        migrations.RemoveField(
            model_name='caja',
            name='monto',
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='DocumentoTributario',
        ),
        migrations.AddField(
            model_name='informediario',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.venta'),
        ),
    ]
