# Generated by Django 4.2.7 on 2023-12-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0005_informediario_remove_caja_monto_alter_venta_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='informediario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(),
        ),
    ]
